name: on.pull-request.main
on:
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
      - Makefile
      - '**.tpl'
      - go.mod
      - go.sum

jobs:
  build:
    name: make test
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install mockery
        run: ./scripts/install_mockery.sh
      - name: make test
        run: make test
      - name: debug
        run: |
          ls -la
          ls -la ~
          ls -la $HOME